services:
  - type: web
    name: educore-app
    runtime: node
    plan: starter
    buildCommand: pnpm install && pnpm -w run build
    preDeployCommand: pnpm --filter @schoolmitra/database db:migrate
    startCommand: pnpm -w run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 10000
